POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "Rajan123",
  "name": "Rajan",
  "password": "RajanSonia",
  "gender": "male",
  "location": "Tenali"
}

###


POST http://localhost:3000/login/
Content-Type: application/json

{
    "username": "Rajan123",
    "password": "SoniaRajan"
}
###

PUT http://localhost:3000/change-password/
Content-Type: application/json

{
  "username": "Rajan123",
  "oldPassword": "RajanSonia",
  "newPassword": "SoniaRajan"
}